sudo: required
addons:
  sauce_connect: true
  firefox: latest
  chrome: stable
language: node_js
node_js:
- 8.17.0
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: npm test && npm run wct-sauce
branches:
  only:
  - master
  - develop
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: $CHANGELOG_GITHUB_TOKEN
    file_glob: true
    file: dist/*
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      branch: master