sudo: required
addons:
  sauce_connect: true
  firefox: latest
  chrome: stable
language: node_js
node_js:
- 8.9.4
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- cp -r node_modules/lit-html ../../lit-html
- ls ../../lit-html/lib

script: npm test && npm run wct-sauce
env:
  global:
  - secure: IczLyQVw0rGAirfVHal4lcPNymjSQewhh2F8vu2rsp6ncNSAkSEVm9tXvSq47UkYzkLEUvi5l2rOIcmnfGsyjc8uCH3yFVpsMdoClP5W+2LO6XB7k6FyV3GXpfotEjKqIXqUWFosbFMdsV5X3zhuouckdvPcrY+QNltVl8P90JqGtVq5VqSIUZVhWsMxelrgY1p0iIx0YdftD0Hq8mip8ULztip+mbAAcLbUBOlOHHRdiG1cNp7GjpaBUPvtVY+/rDM8sgJ7SlK9F+BWsxj5If/Ky3n4HcyvvAAGeiqxJu0jxPQ37JwJKHligE5gK1O/piaAblSsy5kT4ElQXkxJLKLH8SQ7XViJ1NVGzh2AynDnx4J7PzWYfHKMYTbW2/6VaPOR/wr2xj1OdCRlNi8dK7y7Frhml9o58BakCDPx9zJgHd0s9lZQGdGA6O8DD6FpBwK9n8GqzEHI56phgtW8HH9T98r8ZSmm3iggwUesZo12kkkdc9/Eoe3X07G5cxq5r97E/rCnzhFz/uF786FX25H/pDIRUJ9K03VQuBMgG/vkFk1hzMEPjiFqFFXoa6odBR98OwbVFpR0JEpg4vcSRXDXfeNjxy1Pb2HXXSJAR9y2aCEW0U+IL4INPvK40igA/ijp16RP8TsLYszulzwxl8w8EvJTm0eJc1zlMc2QpZI=
  - secure: M8pX7iiBmx8OdCmvMt6sbYSISIUVPYj6Xi52oP0TkOjDN14fxH2OS+Egnui2F9sudNFOgvGoiK4VnE3iH2z8wjFoA1YnbS+wHI1sK862qdtYlxk5pe4HglwrqAH4beg3cBQkN48ds0/gqifMuVxySbKn06KsU7fqMeOV5vunguSpWXbHBT+0vjJAF/J5f6JqZRbw0ggiAWThwqyulIYJPQ+BpYb2hoEhQfmUxGjTisILsNOWzU/qaYojf1PjBgfm7tpRCcvEZxohvqYQx6yCaus5U4I9gWNashpVWlOYbhtdxpRPA2thp2tfZLtuVP6CATeI+YwAcjbPhx4RG9Bxr/TNChh3s0rp4n+wcdXToQtPINnHjcDxK9Wlw+DbAu3tOoxHnhBR7KOWEOCZ3iTlRPMiGivBy5aopf1Lmk+h745PFdTOtF4QAWyY/gwzon1v3HWTwjZxwASSNoc8z4Q05f3vs+Iro9F6FBWsXTFciMpJ7hQ435SmYaX/LCyy3p6iP7W22+mH3vOdGE1yx8LqG3GQ4cRJaUFilRUVAFBF5NOHesB1m8kf1yAjpdqzJT1+/sJEmdmDLCq2WOZor/EjeXvr+4uAy3WvBz3avNKHzZavY/cpHSTTWuwZsLyU16OcQlaIhBWRbmxJj2NWOFI5OjKqXUImJMyp9iifbRTy53I=
